version: '3'
services:
  promo_scheduling:
    build:
      context: .
    volumes:
      - .:/app
      - ${LOCAL_AUTH_KEY_PATH}:/auth/key.json
    ports:
      - 5000:5000
    entrypoint: gunicorn --bind 0.0.0.0:5000 promo_scheduling:app --timeout 90 --log-level debug
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/auth/key.json
      - BQ_PROJECT=${BQ_PROJECT}
      - BQ_DATASET=${BQ_DATASET}
      - BQ_TABLE=${BQ_TABLE}
