version: '3'
services:
  promo_scheduling:
    build:
      context: .
    volumes:
      - .:/app
      - auth/key/path/file.json:/auth/key.json
    ports:
      - 5000:5000
    entrypoint: gunicorn --bind 0.0.0.0:5000 promo_scheduling:app --timeout 90 --log-level debug
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/auth/key.json
